### ISSUE TITLE
Typo in policy metadata field

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#1431]
In the policy `Metadata` protobuf definition, there's a typo in the field name `store_identifer` (should be `store_identifier`). Luckily, because protobuf binary encoding only deals with field numbers, we should be able to safely change the field name without breaking any existing installations. 

We should still test this though. 
- Store some policies in a database store
- Rename the protobuf field and build a new copy of Cerbos
- Try to access the policies stored in the database using the new build

As far as I am aware, the `store_identifier` field is never stored in text format (YAML or JSON) but we should make sure that's definitely the case too.

**Comment by haines** [comment]
HTTP clients use the JSON-encoded messages which include the field name rather than field number, so this would be a breaking change for them.

We could do it safely by deprecating `store_identifer` and adding `store_identifier` as a new field.

**Comment by haines** [comment]
For reasons that are no longer clear to me, the JS SDK sets the `metadata` field on policies to an object with empty values rather than `undefined` 🙈 

https://github.com/cerbos/cerbos-sdk-javascript/blob/5bb905afd64227ed92fc17d92ed417fc08bb6de7/packages/core/src/convert/toProtobuf.ts#L101-L106

This means that `storeIdentifer` (set to an empty string) gets included in `AddOrUpdatePolicy` requests which causes the RPC to fail with an invalid argument error if the field is removed or renamed 😕 

The SDK does also expose this field on the policy metadata returned in `GetPolicy` responses: https://github.com/cerbos/cerbos-sdk-javascript/blob/main/docs/core.policymetadata.md
