### ISSUE TITLE
Does Cerbos support external PIPs?

### ISSUE THREAD

**Issue by obfu5c8** [cerbos/cerbos#1535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Is there already/planned support for inflating resources/principal attributes via external sources as PIPs?

As an example, a PDP-calling consumer may only know the ID of the principal, but policies could require knowing many complex role relationships with other entities. It would be useful if the PDP could hydrate these additional attributes for itself rather than consumers (potentially in several different apps) having to know "everything" up-front.

**Comment by charithe** [comment]
At the moment our focus is on Cerbos as a stateless PDP because that has a lot of advantages in terms of security, performance and scalability. 

Integrating with PIPs is a complicated subject with so many dimensions. One of the most egregious is the fact that a Cerbos instance would need to have credentials to access your data sources and those credentials might have to be overly permissive in order to handle the requests from multiple applications. If there's a security breach and someone manages to compromise a Cerbos instance, they could gain access to a lot of data. 

There are other hairy technical problems to solve in a production environment such as handling different query interfaces because there are so many, caching and correctly refreshing/invalidating cache entries, access control for the clients themselves and so on. As you can imagine, the Cerbos configuration and setup would have to be immensely complicated to deal with all of those issues. That complexity itself would cause security and maintenance nightmares for an organization. 

Our current advice for users who seek PIP integration is to deploy a proxy service in front of Cerbos that can do the attribute hydration on behalf of it. While it might involve a little bit more work, the biggest advantage is that you'd have full control over all aspects of that proxy. You are free to configure and secure it to match the architecture and the requirements of your environment without being limited by what an equivalent, generic PIP integration in  Cerbos would be able to provide.
