### ISSUE TITLE
Allow for evaluating a scope hierarchy with absent top level scope

### ISSUE THREAD

**Issue by scraymondjr** [cerbos/cerbos#1587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Allow for policy evaluation to be performed as long as some level of the scope hierarchy is available for a resource scope. For example, given a resource scope of `a.b.c` and resource policies existing with each of scopes ``, `a`, `a.b`, the policy evaluation of the resource should use these 3 three scopes, ignoring the fact that there is no `a.b.c` policy scope defined. The current behavior results in a `NO_MATCH` and denied response.

### What would the ideal solution look like to you?

Ideally, the default behavior would be to use whatever base hierarchy exists, skipping the higher level scopes that are not defined. An alternative to changing the default behavior (which obviously has backwards compatibility issues), is to add a request option that specifies to find the defined scope hierarchy and to ignore missing top level hierarchies.

**Comment by charithe** [comment]
We do not allow missing scopes because it's a potential source of errors. Cerbos cannot determine whether the scope is missing due to an error or by intention. Ignoring missing scopes could lead to unintended consequences so we err on the side of caution.

**Comment by scraymondjr** [comment]
Fair enough, but that is the reason suggesting of adding a request option that allows the consumer to specify if a missing scope is permissible or not.

**Comment by charithe** [comment]
You can create an empty policy without any rules if a scope is truly optional. That's an explicit signal to other readers about your intent. Otherwise, they'll also have to be aware of how the API calls are being made to Cerbos to truly understand what the policy does. We want the policy repository to be the single source of truth about your access rules.

**Comment by scraymondjr** [comment]
I could do that, but then I lose the ability to define different scopes (obviously). Maybe I can outline the use case I'm wanting to solve and my desired approach. Alternative solution would be good to know, if anyone could help work one out.

I would like to be able to define a resource policy at each of 3 different scopes: system-wide, organization specific, and application specific, where there are many organizations and applications in the system. The organization needs to be able to define their own organization wide policy and applications need to define application specific policy. Further, the organization may be able to define application specific policy. Lastly, the application specific policy is not required.

My idea of the approach for this was to specify a request resource scope based on the organization and application context. Supposing the organization name `foo_org` and app name `bar_app`, the resource scope would be defined as `system.foo_org.bar_app`. My hope was that if a resource policy for scope `system.foo_org.bar_app` was not defined, then the policy engine would simply skip this scope and continue up the hierarchy to `system.foo_org`, `system`, and finally ``.

**Comment by charithe** [comment]
I see. You can model it as I described above with empty policies. But, I can understand why it might not be preferable because it requires creating `num_orgs*num_resources*num_apps` files. Introducing a mode where Cerbos doesn't treat missing scopes as errors is indeed a way to address it. But, it's not quite so straightforward because we can't break existing users. Supporting two modes complicates things quite a bit. I'll need to think about this some more. 

>  I lose the ability to define different scopes (obviously)

I am not sure I understand what you mean by this. Why would you lose the ability to create scopes?
