### ISSUE TITLE
[PostgreSQL] Error while creating schema

### ISSUE THREAD

**Issue by roman-supy-io** [cerbos/cerbos#1669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While executing the SQL script provided at https://docs.cerbos.dev/cerbos/latest/configuration/storage.html#postgres-schema there is an error:
```
error: unterminated dollar-quoted string at or near "$policy_audit$ BEGIN IF (TG_OP = 'DELETE') THEN INSERT INTO policy_revision(action, id, kind, name, version, scope, description, disabled, definition) VALUES('DELETE', OLD.id, OLD.kind, OLD.name, OLD.version, OLD.scope, OLD.description, OLD.disabled, OLD.definition)"
```

### Expected Behavior

Script executes successfully and schema/tables/user are created

### Steps To Reproduce

Log in with root Postgres user (`postgres`), db `postgres`, fresh installation.
Paste the script and execute it.

### Environment

```markdown
- OS: macos ventura 13.3
- PostgreSQL Server version: 15.3
- Cerbos version: <unrelated>
- Docker version: <unrelated>
- Go version: <unrelated>
```

**Comment by charithe** [comment]
Hi. That's odd because we execute that script everyday on a fresh Postgres database for our E2E tests and that issue has never come up. Could it be a copy-paste error or some encoding issue in the browser/OS? Can you try saving and running this script to see if it makes any difference/ https://raw.githubusercontent.com/cerbos/cerbos/main/internal/storage/db/postgres/schema.sql
