### ISSUE TITLE
Discard unknown fields in grpc-gateway?

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#1682]
Currently we have `DiscardUnknown: false` in our grpc-gateway config. This means that we get an invalid argument error when the JSON message includes unknown fields.

However, gRPC calls that include an unknown field succeed (the unknown field is discarded).

I think the behaviour should be consistent.

**Comment by charithe** [comment]
I think the reason it was enabled was because REST API users were getting confused by invalid requests (with typos) being accepted and discarded silently.

With gRPC, you can only have an unknown field if you use a newer version of the protobuf, right? It's more "controlled" in that way compared to JSON.

**Comment by haines** [comment]
Yep, fair enough.

It is a pain in the JS SDK because the gRPC client works after introducing a new field, but the HTTP one doesn't. The problem is really that the generated `toJSON` method doesn't normalize the message, so by including the new field set to the zero value, it makes it into the JSON when it could (should?) be omitted.

Even if we changed this going forward, I'll still need a workaround in the SDK to keep compatibility with earlier versions, so I will have to figure it out 🙂
