### ISSUE TITLE
Change deprecated OTel jaeger exporter

### ISSUE THREAD

**Issue by oguzhand95** [cerbos/cerbos#1784]
```
"go.opentelemetry.io/otel/exporters/jaeger" is deprecated: This module is no longer supported. OpenTelemetry dropped support for Jaeger exporter in July 2023. Jaeger officially accepts and recommends using OTLP. Use [go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp] or [go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc] instead
```

**Comment by muratmirgun** [comment]
Hey I can take this issue

**Comment by emreb** [comment]
Please do. Looking forward to receiving the PR.

**Comment by muratmirgun** [comment]
Guys, I found this in the releases

The go.opentelemetry.io/otel/exporters/jaeger package is deprecated.
OpenTelemetry dropped support for Jaeger exporter in July 2023.
Use go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp
or go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc instead. 

I will make implementation with "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp" that's okay with us?

**Comment by haines** [comment]
We already support otlptracegrpc so I don't think there is anything to be done for this issue, other than we may wish to mark the jaeger exporter as deprecated in the tracing configuration so that we can remove it in a future release.

**Comment by muratmirgun** [comment]
Yes, that is correct. Now you can use it with the otlp client on the Jeager side. We can remove the Jeager option and write this information to Docs. I can open PR for the remove Jeager client side

**Comment by haines** [comment]
I think we should start by documenting the Jaeger exporter as deprecated first, then remove it in a future release, so that anybody who is currently using it has some warning before it disappears.

Let's change the comment on the config section to be prefixed with `[Deprecated]` and include a note that the OTLP exporter should be used instead because Jaeger now supports OTLP.

https://github.com/cerbos/cerbos/blob/f134903b8ddb04dc235eb8d03528f7dc4e79181f/internal/observability/tracing/conf.go#L29

That'll show up in the full configuration docs at https://docs.cerbos.dev/cerbos/latest/configuration/#_full_configuration

Then, let's also update the docs with a similar note about using the OTLP exporter instead.

https://github.com/cerbos/cerbos/blob/f134903b8ddb04dc235eb8d03528f7dc4e79181f/docs/modules/configuration/pages/tracing.adoc?plain=1#L7

Let's also move the OTLP section above the Jaeger one so it has more prominence.

That'll show up at https://docs.cerbos.dev/cerbos/latest/configuration/tracing

I think it would be reasonable to support HTTP as well as gRPC. We could add a `Protocol` field to the config that would default to `"grpc"` but could also be set to `"http/protobuf"` (per the [docs](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#specify-protocol) they also have an `"http/json"` protocol, but we won't support that because their Go SDK doesn't support that).

https://github.com/cerbos/cerbos/blob/main/internal/observability/tracing/conf.go#L50-L53

Hope that helps you get started @muratmirgun! Thanks for contributing 🙇

**Comment by muratmirgun** [comment]
Thanks for the info. I am working on it  🚀
