### ISSUE TITLE
Confusing error message when a policy file isn't terminated by a newline

### ISSUE THREAD

**Issue by dbuduev** [cerbos/cerbos#2019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

A policy file must end with a newline character. Cerbos fails to parse it otherwise. The problem is in confusing error messages.

### What would the ideal solution look like to you?

A clear error message like "Please ensure a trailing newline at the end of policy definitions" is needed.

**Comment by charithe** [comment]
Do you have an example of this? I can't reproduce it.

**Comment by charithe** [comment]
OK, managed to reproduce it. It looks like the fold operator (`>`) removes the last character of the string regardless of whether it's a newline or not. Curiously, the literal operator (`|`) doesn't have this problem.

If you have a very aggressive editor that removes all line feeds from the end of the file, then you'd run into this issue. Mine is configured to remove all trailing spaces too but it's not so aggressive as to remove the line feed at the end of the line. I had to explicitly truncate the last byte using `truncate -s -1 file.yaml` to reproduce this problem.

This fails because there's no line feed at the end.

```
apiVersion:·api.cerbos.dev/v1␊
resourcePolicy:␊
··version:·"default"␊
··resource:·"foo"␊
··rules:␊
····-·actions:·[·'view'·]␊
······effect:·EFFECT_ALLOW␊
······roles:·[·'user'·]␊
······condition:␊
········match:␊
··········expr:·>␊
············R.attr.accountId·==·P.attr.accountId·&&␊
············(␊
··············(R.attr.creatorId·==·P.id·&&·R.attr.status·==·"draft")·||␊
··············(has(P.attr.roles.admin)·&&·R.attr.creator.orgUnitIds·in·P.attr.roles.admin)·||␊
··············(R.attr.type·==·"organizational"·&&·R.attr.status·==·"published")␊
············)
```

Notice that the final bracket is missing from the expression. Which means that the `>` operator must have removed it.

```
Invalid expression: `R.attr.accountId == P.attr.accountId && (   (R.attr.creatorId == P.id && R.attr.status == "draft") ||   (has(P.attr.roles.admin) && R.attr.creator.orgUnitIds in P.attr.roles.admin) ||   (R.attr.type == "organizational" && R.attr.status == "published")` <failed to compile `R.attr.accountId == P.attr.accountId && (   (R.attr.creatorId == P.id && R.attr.status == "draft") ||   (has(P.attr.roles.admin) && R.attr.creator.orgUnitIds in P.attr.roles.admin) ||   (R.attr.type == "organizational" && R.attr.status == "published")` [Syntax error: missing ')' at '<EOF>']>
```

This works because there's a line feed after the last bracket.

```
apiVersion:·api.cerbos.dev/v1␊
resourcePolicy:␊
··version:·"default"␊
··resource:·"foo"␊
··rules:␊
····-·actions:·[·'view'·]␊
······effect:·EFFECT_ALLOW␊
······roles:·[·'user'·]␊
······condition:␊
········match:␊
··········expr:·>␊
············R.attr.accountId·==·P.attr.accountId·&&␊
············(␊
··············(R.attr.creatorId·==·P.id·&&·R.attr.status·==·"draft")·||␊
··············(has(P.attr.roles.admin)·&&·R.attr.creator.orgUnitIds·in·P.attr.roles.admin)·||␊
··············(R.attr.type·==·"organizational"·&&·R.attr.status·==·"published")␊
············)␊
```

The `|` operator doesn't have this issue even if there's no line feed at the end. This works just fine.

```
apiVersion:·api.cerbos.dev/v1␊
resourcePolicy:␊
··version:·"default"␊
··resource:·"foo"␊
··rules:␊
····-·actions:·[·'view'·]␊
······effect:·EFFECT_ALLOW␊
······roles:·[·'user'·]␊
······condition:␊
········match:␊
··········expr:·|␊
············R.attr.accountId·==·P.attr.accountId·&&␊
············(␊
··············(R.attr.creatorId·==·P.id·&&·R.attr.status·==·"draft")·||␊
··············(has(P.attr.roles.admin)·&&·R.attr.creator.orgUnitIds·in·P.attr.roles.admin)·||␊
··············(R.attr.type·==·"organizational"·&&·R.attr.status·==·"published")␊
············)
```

I'll look into why `>` is doing this. In the mean time, the solution is to use the `|` operator.

**Comment by charithe** [comment]
https://github.com/goccy/go-yaml/pull/434
