### ISSUE TITLE
Deprecate `storage.git.protocol` and infer the protocol from `storage.git.url`'s scheme

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#2162]
I think it's redundant to have to specify `protocol` and `url` separately; it allows you to set them to incompatible values. Also, go-git behaves badly when the scheme is omitted from the URL and falls back to loading from the local filesystem even if the protcol is not set to `file`.

We should infer the protocol from the URL scheme and reject values that do not have one of the supported schemes.

https://cerboscommunity.slack.com/archives/C02A364JYMQ/p1716470276123109

**Comment by charithe** [comment]
IIRC, the reason for splitting this up was due to the Go URL parser not being able to handle the SCP-style (`user@gihub.com:org/repo.git`) URLs. In fact, if you pass a URL like `ssh://user@github.com:org/repo.git`, go-git itself fails to handle it.

The `protocol` field also determines the additional auth config section to use (`ssh` or `https`). That's consistent with how our other configuration sections work (`driver: foo` indicates that `foo` section is active and so on). 

So, instead of deprecating the `protocol` field, I think we can do a bit more validation instead. If the protocol is `https` or `file`, we can try to inject the scheme to URLs that are lacking it.
