### ISSUE TITLE
Checksum mismatch: go get github.com/google/flatbuffers/go

### ISSUE THREAD

**Issue by mertakman** [cerbos/cerbos#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running go mod tidy, it is raising an error because of an issue mentioned in [here](https://github.com/google/flatbuffers/issues/6466). And not making the repository build at other environments. 

### Expected Behavior

It should download normally during the go mod tidy operations. All module hashes must match with the actual release hashes of GitHub. Possibly if the version with the previous hash is already installed on computer, please consider run go clean -modcache previously for not getting the previous version of protobuf from the cache of the current computer. 

### Steps To Reproduce

In any environment installed Golang just download the repository via git clone,
Run go mod tidy 

### Environment

```markdown
- OS:Ubuntu 20.04
- Cerbos version:0.4.0
- Docker version: - 
- Go version: -
```

### Anything else?

Google re-released the protobuf library under same release number , and it causing go mod tidy to crash .

**Comment by charithe** [comment]
Can you provide more details about what you tried to do? The output of `go env` would be helpful too.

I launched a fresh Ubuntu VM and ran `go mod tidy` on HEAD (66a8164fa90937a44c43c8c41bcccb4a7b566991) and there was no issue.

**Comment by mertakman** [comment]
https://github.com/google/flatbuffers/issues/6466
details can be found in here , this repo has the old hash , and when I run go mod tidy , here is the output 

```
verifying github.com/google/flatbuffers@v1.12.0: checksum mismatch
        downloaded: h1:N8EguYFm2wwdpoNcpchQY0tPs85vOJkboFb2dPxmixo=
        go.sum:     h1:/PtAHvnBY4Kqnx/xCQ3OIV9uYcSFGScBsWI3Oogeh6w=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

It can be caused by fresh Ubuntu VM is getting goproxy from google's defaults . 
Maybe you can try using 
GOPROXY=direct go mod download github.com/google/flatbuffers@v1.12.0 , and that can make sense.

**Comment by charithe** [comment]
> It can be caused by fresh Ubuntu VM is getting goproxy from google's defaults .

This is the reason why I want to get to the bottom of this issue because it sounds like an environmental problem. Are you using a different Go proxy from the defaults? Even in the original issue, the problem went away for some people after they changed their proxy. (Again, the output from `go env` could be helpful here).

Flatbuffers is a transitive dependency of this project, pulled in by BadgerDB. I didn't want to simply override the version unilaterally because it might not have been tested with Badger. But, I see Badger has a new patch version out which uses flatbuffers 2.0.0 so I will look into upgrading to that. 

In the meantime, please feel free to use the release artifacts from https://github.com/cerbos/cerbos/releases to try out Cerbos.
