### ISSUE TITLE
Wrap errors to bring more detailed errors

### ISSUE THREAD

**Issue by isdevx** [cerbos/cerbos#279]
There are several unwrapped errors in the codebase that could be wrapped to make debugging much easier. For instance in the https://github.com/cerbos/cerbos/blob/main/client/admin.go file, there are some errors could be wrapped to bring a better error tracing. 

Let's take this error as an [example](https://github.com/cerbos/cerbos/blob/5fd29cd799747299f5bfbacb74b896b81df850d8/client/admin.go#L142): 
```Go
func (c *GrpcAdminClient) auditLogs(ctx context.Context, opts AuditLogOptions) (svcv1.CerbosAdminService_ListAuditLogEntriesClient, error) {
	...
	if err := req.Validate(); err != nil {
		return nil, err
	}
	...
}
```
We are convey the information that request is not valid but we don't mention in which step the error is occurred. We can add an information that the request validation failed while requesting audit logs.

**Comment by charithe** [comment]
In case I missed something, can you explain what you would wrap here? The `Validate` method in this example actually produces  pretty good information about what validation checks failed. 

Can you add some more examples from the list you mentioned as well please?

**Comment by isdevx** [comment]
I didn't mean that validation error is not informative, I am saying that when it's happened. Let's take this error as an example:
`ERROR: could not get decision logs: invalid ListAuditLogEntriesRequest.Lookup ..."` 
If we wrapped the error we could add an information like 
`ERROR: could not get decision logs: could not validate audit log request: invalid ListAuditLogEntriesRequest ..."`
It's a bit verbose I can agree, but we shouldn't expecting everyone to be pro enough to understand.

**Comment by charithe** [comment]
I get the point you're making and agree wholeheartedly that error messages in general could be better.  However, if I am being pedantic, "could not validate audit log request" and "invalid ListAuditLogEntriesRequest" is the same thing worded just slightly differently. Neither gives me a solution to the problem itself -- which is what a user really wants.  

I think we spoke about this 1:1. I am not convinced that the solution to the problem is as simple as "wrap all errors". If you wrap the error just before sending it to the user, you don't have a lot of context about what actually went wrong and all you can do is just try to soften the blow by saying something generic.  If you wrap errors religiously through the entire call chain, you can actually make it difficult to handle some errors because they need to be unwrapped first to do anything useful with them. Also, programmer fatigue would set in very soon and the supposedly helpful messages are going to be less and less so.  

Let's try to figure out a good, preferably mechanical, solution for this. We already have some prior art in the code base in the form of codegen and compile errors we produce but they are by no means perfect and they were a pain to work with as well. Hopefully, there are better alternatives.
