### ISSUE TITLE
Support  https://github.com/golioth/grpc-websocket-proxy

### ISSUE THREAD

**Issue by gedw99** [cerbos/cerbos#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

At the moment GRPC gateway is used. 

Its very heavy and slow. 

### What would the ideal solution look like to you?

GRPC-WebSocket-Proxy allows the GRPC-web and non web ( TCP ) to work inside the same binary.
Its fast and light.

It also works with golang ( compiled to wasm ) and JS ( like react ).

Here is a nice and concise example showing that. https://github.com/tmc/goloz
its compiling the protobufs to golang and WASM, and its accessible in the client using react
It supports the TCP based GRPC and the WebSockets based GRPC.

You can still keep the grpc gateway for more traditional REST style API.

### Anything else?

Great project btw.

Here you use REST and TCP GRPC: https://github.com/cerbos/cerbos-aws-lambda/blob/main/gateway/launcher.go

GRPC-WebSocket-Proxy means you only need one server process ( its essentially embedded in the main cerbos binary ) and port allocation because GRPC-WebSocket-Proxy is just another API using websockets.

I am reasonably sure that there will be no of minimal code changes, but have no had time to try it yet.

You can compile the golang to Tinygo wasm and so the wasm goes from 1 MB down to 20 kb. 

You can also compile to JS, if you don't want the WASM, which i can understand perhaps you don't want.

**Comment by charithe** [comment]
Thanks for your interest in Cerbos. What is the use case you are trying to address?

I am not sure I understand the rationale for your proposal. All our external APIs are unidirectional and not meant to be directly accessible from a browser. So, I am not convinced that we'd get any benefit from either websockets or wasm at this point. The proposed `grpc-websocket-proxy` project still uses `grpc-gateway` behind the scenes so I don't see how it would help us get rid of `grpc-gateway` either. 

The AWS Lambda launcher (https://github.com/cerbos/cerbos-aws-lambda) is a supplementary project that wraps Cerbos to run within the Lambda environment. It bundles the Lambda gateway and launches Cerbos as a separate process to handle requests. We decided to do it that way because we wanted to keep the vendor-specific code out of the main Cerbos source tree.

**Comment by gedw99** [comment]
Thanks that’s makes sense .

i will use the lambs approach
