### ISSUE TITLE
Add function to get current timestamp

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#667]
Add a CEL function to get the current server timestamp. What would be a good name: `now`, `currentTimestamp` or both?

**Comment by haines** [comment]
I marginally prefer `now` on the grounds of brevity. I don't think there's a strong reason to do both - I would prefer it if there were one way to do it, because I feel like it could be confusing if different policies used different functions (it would beg the question if these were returning different results).

Would repeated invocation of the function within a single expression return the exact same timestamp? I think this is the most "correct" behaviour - although unlikely to make much practical difference, it would be in line with the behaviour of `current_timestamp`/`now()` in SQL, where the return value is the start time of the transaction rather than the exact instance the function is invoked.

i.e. I would expect this invariant to hold

```
now() == now()
```

**Comment by charithe** [comment]
Those are very good points. I am not sure whether we could easily guarantee that `now() == now()` in the CEL environment because AFAIK there's no concept of a transaction. If we implement `now()` as a function, it becomes part of the global scope and I am not aware of a way in which it could maintain some state to ensure that within a particular execution scope it produces the same value. 
 
A workaround would be to tell users to define a policy variable that holds the value of `now()`. It would guarantee that within the scope of that policy the value of the variable would not change.

**Comment by charithe** [comment]
Cool! Would you like to create a PR? :-)
