### ISSUE TITLE
Principal id attribute data type

### ISSUE THREAD

**Issue by KonstantinosPetrakis** [cerbos/cerbos#798]
While using Cerbos, I realized that when making a request, the **principal** object's attribute i**d must be a string**. Isn't that kind of **inefficient** taking into account that **most IDs** in common databases **are integers?** One has to write some lines of code for each resource or principal object **converting** their I**Ds from integers to strings**. Would it be **bad practice** to "cast" all my object's IDs, is there any away of doing that inside resource definition file? 

Correct me if I am wrong, when I tried to pass an integer ID in the principle object I always got **unauthorized**, moreover the intelisense of my IDE tells me it has to be string when using the NODE SDK. 

Thanks in advance.

**Comment by oguzhand95** [comment]
We use a strongly-typed schema ([protobuf](https://github.com/cerbos/cerbos/blob/main/api/public/cerbos/engine/v1/engine.proto#L162)) to represent all the data structures.

For IDs, we have to use the lowest common denominator that can generalize to all possible use cases. (There is no guarantee that all IDs are integers. UUIDs are a common way to represent IDs, for example)

There are highly optimized algorithms for that conversion -- so the performance hit (if any) is negligible.

**Comment by charithe** [comment]
> Isn't that kind of **inefficient** taking into account that **most IDs** in common databases **are integers**

I'd also like to add that in a security context, it wouldn't be a good idea to have an integer as the user ID because an attacker can very quickly iterate through all possible user IDs when crafting an attack (to quickly enumerate all the valid users in the system, for example).

As @oguzhand95 said, performance of string to integer conversion is negligible in this context. There are efficient algorithms for this. SWAR (SIMD within a register) and https://lemire.me/blog/2021/01/29/number-parsing-at-a-gigabyte-per-second/ (implemented in the Go standard library) are examples of recent innovations in this area. If you look at some of the benchmarks such as https://www.zverovich.net/2020/06/13/fast-int-to-string-revisited.html, even the _slowest_ implementation can handle nearly 3 million conversions/second -- which is quite a lot!

**Comment by KonstantinosPetrakis** [comment]
I have no Go knowledge. When I asked the question, I thought about a function template or a Union structure (C-like) but you made it loud and clear that anything like it (a generalization) is not worth the trouble.

Considering UUIDs @oguzhand95 mentioned and the security matters @charithe briefly discussed I think the problem is with me, not have worked in industrial code enough to have thought about it, but I guess we all started from somewhere.

Given the strongly typed schema, it totally makes sense to be a string. Thanks for your trouble.
