### ISSUE TITLE
PlanResources API: "FilterDebug" should reflect normalised AST

### ISSUE THREAD

**Issue by dbuduev** [cerbos/cerbos#964]
An AST debug string representation is currently built before the AST is normalised. Hence in the string representation variables are not expanded, and logical expressions are not optimised.

Ideally, the AST debug string should reflect the final AST.

Additionally,  `NOT true` and `NOT false` expressions have to be optimised.

**Comment by charithe** [comment]
So, the tricky bit here is that `filterDebug` is produced from the AST where we use the CEL parser to produce the expressions in their infix form. 
The normalisation happens at the high level filter representation much later in the process. We _could_ produce the expression by traversing the filter but it will probably come out looking a bit like S-expressions (`eq(R.id, "blah")`) unless we put a lot of effort into making them look "natural" -- which I think is not worth it.

**Comment by charithe** [comment]
This is what the output looks like:

```clojure
(and (and (eq request.resource.attr.geography "GB") (eq request.resource.attr.geography "GB")) (eq request.resource.attr.status "PENDING_APPROVAL"))
```

It's extremely easy to parse and probably can be `eval`ed directly in a Lisp-y language like Clojure. Whether it's easy for humans to read is quite subjective.

Alternatively, we can keep the existing `filterDebug` representation derived from the un-normalised AST. It can be argued that it is more of a "debug" aid because it represents the raw plan generated from the policies before any optimisations were applied.
