### ISSUE TITLE
Cache JWT verification status

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#991]
We currently perform the verification step on `auxData.jwt` for every request. Although this is relatively quick, we can probably cache the verification status to make it even faster.

We should be careful not to cache the token beyond its expiry. In a busy environment, there could be lots of tokens to cache so we need to be careful about not using up a lot of memory for the cache as well.

**Comment by rasmusdencker** [comment]
One way would be implementing an ARC Cache with a configurable size so that the operations person can control the theoretical memory limit used by the cache, given their average token size. 

I think the most efficient implementation would be placing an empty struct in the cache, using the plaintext token as the cache key once it's been verified the first time. On the next request, if the jwt is in the cache, it'll skip the `jwt.WithKeySet` option, but still call `jwt.Parse` with the `jwt.Validate` option (the 'heavy' part is the verification step). 

When doing so, it will [still validate the exp claim](https://github.com/lestrrat-go/jwx/blob/e033e1cf3358760dc718800bcbd122f312056f20/jwt/validate.go#L51) on every request, ultimately ensuring that no expired token will ever be allowed.
